spring.application.name=interstellartransportsystem
spring.datasource.url=jdbc:derby:myDB;create=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.DerbyDialect
spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
spring.jpa.defer-datasource-initialization=true
#spring.jpa.hibernate.ddl-auto=update
#debug=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

server.port=8080

spring.jpa.hibernate.ddl-auto=create-drop